### ISSUE TITLE
Aptitude install fails 

### ISSUE THREAD

**Issue by bra1ncramp** [cisagov/ubuntu-server-packer#12]
# 🐛 Summary #

`aptitude` sporadically fails to install during packer AMI build. Sometimes we have to re-run the tasks multiple times before it successfully installs and moves on.

The following articles suggest that we need to explicitly run `apt-get update` first:
https://github.com/Oefenweb/ansible-apt/pull/8/files
https://weisser-zwerg.dev/posts/local-discourse-on-vagrant/
http://wiki.shopingserver.com/ansible-not-find-aptitude-please-ensure-installed-error-solution/

So that is what we currently do to mitigate this issue:
https://github.com/cisagov/ubuntu-server-packer/blob/99c815cdc134bcd03a79fae3b8437eae0713546f/src/packer.pkr.hcl#L108-L111

The Ansible role that calls this is found here:
https://github.com/cisagov/ansible-role-upgrade/blob/develop/tasks/apt.yml

Ideally, https://github.com/cisagov/ansible-role-upgrade could be modified to eliminate the need for us to run `apt-get update` when building this AMI.

## Helpful log output ##

```amazon-ebs.ubuntu_server: TASK [upgrade : Install aptitude] **********************************************
amazon-ebs.ubuntu_server: fatal: [default]: FAILED! => {"changed": false, "msg": "No package matching 'aptitude' is available"}
amazon-ebs.ubuntu_server:
 amazon-ebs.ubuntu_server: PLAY RECAP *********************************************************************
 amazon-ebs.ubuntu_server: default                    : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by jsf9k** [comment]
I haven't seen this issue, so I'll close it and reopen it later if necessary.
