### ISSUE TITLE
Use master branch of ansible-role-hardening-2 after cisagov-changes branch is merged

### ISSUE THREAD

**Issue by bra1ncramp** [cisagov/ubuntu-server-packer#16]
# 💡 Summary #

Currently, we are using https://github.com/cisagov/ansible-role-hardening-2/tree/cisagov-changes to harden our Ubuntu server.

After the `cisagov-changes` branch has been merged into the default branch, we should revert the change in https://github.com/cisagov/ubuntu-server-packer/commit/81f01a4cc479208c987a6903af3b29ad5a155138 so that we point to the default branch.

Additionally, the TODO comment added in https://github.com/cisagov/ubuntu-server-packer/commit/4feb302f8b03006e30c3b3c8263be9dd369990f8 should also be removed.

**Comment by jsf9k** [comment]
Resolved by #19.
